### ISSUE TITLE
"Caught an Exception"

### ISSUE THREAD

**Issue by abhaytalreja** [apollographql/frontpage-react-native-app#1]
Just tried the basic clone, npm install and run... getting the below exception.

![image](https://cloud.githubusercontent.com/assets/1915902/20402176/a9acc0da-acc9-11e6-8488-d7c3ec730198.png)

![image](https://cloud.githubusercontent.com/assets/1915902/20402196/bcc3562a-acc9-11e6-8415-737683eb543d.png)

**Comment by stubailo** [comment]
I thought React Native supports `fetch` out of the box?

**Comment by eschapp** [comment]
You need to have the Front Page Server running as well. I had the same issue initially, and I missed that step.
